#ifndef TEXPCONSTS
#define TEXPCONSTS

#line 4 "texpconsts.hpp" 
#include "fixedstr.hpp"
namespace text {
extern const char * _line_FULL;
extern const char * _column_FULL;
extern const char * _type_FULL;
extern const char * _start_FULL;
extern const char * _end_FULL;
extern const char * _range_FULL;
extern const char * _loc_FULL;
extern const char * _value_FULL;
extern const char * _Identifier_FULL;
extern const char * _Punctuator_FULL;
extern const char * _name_FULL;
extern const char * _object_FULL;
extern const char * _property_FULL;
extern const char * _computed_FULL;
extern const char * _MemberExpression_FULL;
extern const char * _Keyword_FULL;
extern const char * _operator_FULL;
extern const char * _left_FULL;
extern const char * _right_FULL;
extern const char * _raw_FULL;
extern const char * _Literal_FULL;
extern const char * _expression_FULL;
extern const char * _arguments_FULL;
extern const char * _callee_FULL;
extern const char * _CallExpression_FULL;
extern const char * _init_FULL;
extern const char * _body_FULL;
extern const char * _id_FULL;
extern const char * _ExpressionStatement_FULL;
extern const char * _kind_FULL;
extern const char * _Numeric_FULL;
extern const char * _BinaryExpression_FULL;
extern const char * _String_FULL;
extern const char * _AssignmentExpression_FULL;
extern const char * _var_FULL;
extern const char * _BlockStatement_FULL;
extern const char * _key_FULL;
extern const char * _this_FULL;
extern const char * _ThisExpression_FULL;
extern const char * _VariableDeclarator_FULL;
extern const char * _argument_FULL;
extern const char * _Property_FULL;
extern const char * _test_FULL;
extern const char * _params_FULL;
extern const char * _consequent_FULL;
extern const char * _function_FULL;
extern const char * _defaults_FULL;
extern const char * _rest_FULL;
extern const char * _generator_FULL;
extern const char * _alternate_FULL;
extern const char * _declarations_FULL;
extern const char * _VariableDeclaration_FULL;
extern const char * _LogicalExpression_FULL;
extern const char * _FunctionExpression_FULL;
extern const char * _prefix_FULL;
extern const char * _return_FULL;
extern const char * _ReturnStatement_FULL;
extern const char * _if_FULL;
extern const char * _IfStatement_FULL;
extern const char * _UnaryExpression_FULL;
extern const char * _properties_FULL;
extern const char * _ObjectExpression_FULL;
extern const char * _elements_FULL;
extern const char * _ArrayExpression_FULL;
extern const char * _ConditionalExpression_FULL;
extern const char * _expressions_FULL;
extern const char * _SequenceExpression_FULL;
extern const char * _Boolean_FULL;
extern const char * _Null_FULL;
extern const char * _UpdateExpression_FULL;
extern const char * _for_FULL;
extern const char * _FunctionDeclaration_FULL;
extern const char * _update_FULL;
extern const char * _else_FULL;
extern const char * _ForStatement_FULL;
extern const char * _new_FULL;
extern const char * _NewExpression_FULL;
extern const char * _index_FULL;
extern const char * _typeof_FULL;
extern const char * _get_FULL;
extern const char * _in_FULL;
extern const char * _SwitchCase_FULL;
extern const char * _label_FULL;
extern const char * _each_FULL;
extern const char * _case_FULL;
extern const char * _RegularExpression_FULL;
extern const char * _break_FULL;
extern const char * _BreakStatement_FULL;
extern const char * _set_FULL;
extern const char * _delete_FULL;
extern const char * _ForInStatement_FULL;
extern const char * _instanceof_FULL;
extern const char * _while_FULL;
extern const char * _message_FULL;
extern const char * _param_FULL;
extern const char * _handlers_FULL;
extern const char * _block_FULL;
extern const char * _throw_FULL;
extern const char * _ThrowStatement_FULL;
extern const char * _WhileStatement_FULL;
extern const char * _source_FULL;
extern const char * _finalizer_FULL;
extern const char * _try_FULL;
extern const char * _guardedHandlers_FULL;
extern const char * _TryStatement_FULL;
extern const char * _catch_FULL;
extern const char * _CatchClause_FULL;
extern const char * _cases_FULL;
extern const char * _tokens_FULL;
extern const char * _switch_FULL;
extern const char * _discriminant_FULL;
extern const char * _SwitchStatement_FULL;
extern const char * _continue_FULL;
extern const char * _ContinueStatement_FULL;
extern const char * _regexp_FULL;
extern const char * _default_FULL;
extern const char * _class_FULL;
extern const char * _do_FULL;
extern const char * _DoWhileStatement_FULL;
extern const char * _Program_FULL;
extern const char * _EmptyStatement_FULL;
extern const char * _void_FULL;
extern const char * _finally_FULL;
extern const char * _LabeledStatement_FULL;
extern const char * _errors_FULL;
extern const char * _Line_FULL;
extern const char * _with_FULL;
extern const char * _program_FULL;
extern const char * _lineNumber_FULL;
extern const char * _description_FULL;
extern const char * _WithStatement_FULL;
extern const char * _extends_FULL;
extern const char * _debugger_FULL;
extern const char * _import_FULL;
extern const char * _export_FULL;
extern const char * _DebuggerStatement_FULL;
extern const char * _comments_FULL;
extern const char * _isAssert_FULL;
extern const char * _isError_FULL;
extern const char * _leadingComments_FULL;
extern const char * _trailingComments_FULL;
extern const char * _regexpBody_FULL;
extern const char * _regexpFlags_FULL;
extern const char * _ArrowFunctionExpression_FULL;
extern const char * _ArrowParameterPlaceholder_FULL;
extern const char * _Block_FULL;
extern const char * _const_FULL;
extern const char * _ZendZ_FULL;
extern const char * _enum_FULL;
extern const char * _let_FULL;
extern const char * _super_FULL;
extern const char * _UnresolvedNode_FULL;
extern const char * _yield_FULL;
#ifndef NOTEXP
extern const char * _line_;
extern const fixedstr::SFixedStr _line;
extern const char * _column_;
extern const fixedstr::SFixedStr _column;
extern const char * _type_;
extern const fixedstr::SFixedStr _type;
extern const char * _start_;
extern const fixedstr::SFixedStr _start;
extern const char * _end_;
extern const fixedstr::SFixedStr _end;
extern const char * _range_;
extern const fixedstr::SFixedStr _range;
extern const char * _loc_;
extern const fixedstr::SFixedStr _loc;
extern const char * _value_;
extern const fixedstr::SFixedStr _value;
extern const char * _Identifier_;
extern const fixedstr::SFixedStr _Identifier;
extern const char * _Punctuator_;
extern const fixedstr::SFixedStr _Punctuator;
extern const char * _name_;
extern const fixedstr::SFixedStr _name;
extern const char * _object_;
extern const fixedstr::SFixedStr _object;
extern const char * _property_;
extern const fixedstr::SFixedStr _property;
extern const char * _computed_;
extern const fixedstr::SFixedStr _computed;
extern const char * _MemberExpression_;
extern const fixedstr::SFixedStr _MemberExpression;
extern const char * _Keyword_;
extern const fixedstr::SFixedStr _Keyword;
extern const char * _operator_;
extern const fixedstr::SFixedStr _operator;
extern const char * _left_;
extern const fixedstr::SFixedStr _left;
extern const char * _right_;
extern const fixedstr::SFixedStr _right;
extern const char * _raw_;
extern const fixedstr::SFixedStr _raw;
extern const char * _Literal_;
extern const fixedstr::SFixedStr _Literal;
extern const char * _expression_;
extern const fixedstr::SFixedStr _expression;
extern const char * _arguments_;
extern const fixedstr::SFixedStr _arguments;
extern const char * _callee_;
extern const fixedstr::SFixedStr _callee;
extern const char * _CallExpression_;
extern const fixedstr::SFixedStr _CallExpression;
extern const char * _init_;
extern const fixedstr::SFixedStr _init;
extern const char * _body_;
extern const fixedstr::SFixedStr _body;
extern const char * _id_;
extern const fixedstr::SFixedStr _id;
extern const char * _ExpressionStatement_;
extern const fixedstr::SFixedStr _ExpressionStatement;
extern const char * _kind_;
extern const fixedstr::SFixedStr _kind;
extern const char * _Numeric_;
extern const fixedstr::SFixedStr _Numeric;
extern const char * _BinaryExpression_;
extern const fixedstr::SFixedStr _BinaryExpression;
extern const char * _String_;
extern const fixedstr::SFixedStr _String;
extern const char * _AssignmentExpression_;
extern const fixedstr::SFixedStr _AssignmentExpression;
extern const char * _var_;
extern const fixedstr::SFixedStr _var;
extern const char * _BlockStatement_;
extern const fixedstr::SFixedStr _BlockStatement;
extern const char * _key_;
extern const fixedstr::SFixedStr _key;
extern const char * _this_;
extern const fixedstr::SFixedStr _this;
extern const char * _ThisExpression_;
extern const fixedstr::SFixedStr _ThisExpression;
extern const char * _VariableDeclarator_;
extern const fixedstr::SFixedStr _VariableDeclarator;
extern const char * _argument_;
extern const fixedstr::SFixedStr _argument;
extern const char * _Property_;
extern const fixedstr::SFixedStr _Property;
extern const char * _test_;
extern const fixedstr::SFixedStr _test;
extern const char * _params_;
extern const fixedstr::SFixedStr _params;
extern const char * _consequent_;
extern const fixedstr::SFixedStr _consequent;
extern const char * _function_;
extern const fixedstr::SFixedStr _function;
extern const char * _defaults_;
extern const fixedstr::SFixedStr _defaults;
extern const char * _rest_;
extern const fixedstr::SFixedStr _rest;
extern const char * _generator_;
extern const fixedstr::SFixedStr _generator;
extern const char * _alternate_;
extern const fixedstr::SFixedStr _alternate;
extern const char * _declarations_;
extern const fixedstr::SFixedStr _declarations;
extern const char * _VariableDeclaration_;
extern const fixedstr::SFixedStr _VariableDeclaration;
extern const char * _LogicalExpression_;
extern const fixedstr::SFixedStr _LogicalExpression;
extern const char * _FunctionExpression_;
extern const fixedstr::SFixedStr _FunctionExpression;
extern const char * _prefix_;
extern const fixedstr::SFixedStr _prefix;
extern const char * _return_;
extern const fixedstr::SFixedStr _return;
extern const char * _ReturnStatement_;
extern const fixedstr::SFixedStr _ReturnStatement;
extern const char * _if_;
extern const fixedstr::SFixedStr _if;
extern const char * _IfStatement_;
extern const fixedstr::SFixedStr _IfStatement;
extern const char * _UnaryExpression_;
extern const fixedstr::SFixedStr _UnaryExpression;
extern const char * _properties_;
extern const fixedstr::SFixedStr _properties;
extern const char * _ObjectExpression_;
extern const fixedstr::SFixedStr _ObjectExpression;
extern const char * _elements_;
extern const fixedstr::SFixedStr _elements;
extern const char * _ArrayExpression_;
extern const fixedstr::SFixedStr _ArrayExpression;
extern const char * _ConditionalExpression_;
extern const fixedstr::SFixedStr _ConditionalExpression;
extern const char * _expressions_;
extern const fixedstr::SFixedStr _expressions;
extern const char * _SequenceExpression_;
extern const fixedstr::SFixedStr _SequenceExpression;
extern const char * _Boolean_;
extern const fixedstr::SFixedStr _Boolean;
extern const char * _Null_;
extern const fixedstr::SFixedStr _Null;
extern const char * _UpdateExpression_;
extern const fixedstr::SFixedStr _UpdateExpression;
extern const char * _for_;
extern const fixedstr::SFixedStr _for;
extern const char * _FunctionDeclaration_;
extern const fixedstr::SFixedStr _FunctionDeclaration;
extern const char * _update_;
extern const fixedstr::SFixedStr _update;
extern const char * _else_;
extern const fixedstr::SFixedStr _else;
extern const char * _ForStatement_;
extern const fixedstr::SFixedStr _ForStatement;
extern const char * _new_;
extern const fixedstr::SFixedStr _new;
extern const char * _NewExpression_;
extern const fixedstr::SFixedStr _NewExpression;
extern const char * _index_;
extern const fixedstr::SFixedStr _index;
extern const char * _typeof_;
extern const fixedstr::SFixedStr _typeof;
extern const char * _get_;
extern const fixedstr::SFixedStr _get;
extern const char * _in_;
extern const fixedstr::SFixedStr _in;
extern const char * _SwitchCase_;
extern const fixedstr::SFixedStr _SwitchCase;
extern const char * _label_;
extern const fixedstr::SFixedStr _label;
extern const char * _each_;
extern const fixedstr::SFixedStr _each;
extern const char * _case_;
extern const fixedstr::SFixedStr _case;
extern const char * _RegularExpression_;
extern const fixedstr::SFixedStr _RegularExpression;
extern const char * _break_;
extern const fixedstr::SFixedStr _break;
extern const char * _BreakStatement_;
extern const fixedstr::SFixedStr _BreakStatement;
extern const char * _set_;
extern const fixedstr::SFixedStr _set;
extern const char * _delete_;
extern const fixedstr::SFixedStr _delete;
extern const char * _ForInStatement_;
extern const fixedstr::SFixedStr _ForInStatement;
extern const char * _instanceof_;
extern const fixedstr::SFixedStr _instanceof;
extern const char * _while_;
extern const fixedstr::SFixedStr _while;
extern const char * _message_;
extern const fixedstr::SFixedStr _message;
extern const char * _param_;
extern const fixedstr::SFixedStr _param;
extern const char * _handlers_;
extern const fixedstr::SFixedStr _handlers;
extern const char * _block_;
extern const fixedstr::SFixedStr _block;
extern const char * _throw_;
extern const fixedstr::SFixedStr _throw;
extern const char * _ThrowStatement_;
extern const fixedstr::SFixedStr _ThrowStatement;
extern const char * _WhileStatement_;
extern const fixedstr::SFixedStr _WhileStatement;
extern const char * _source_;
extern const fixedstr::SFixedStr _source;
extern const char * _finalizer_;
extern const fixedstr::SFixedStr _finalizer;
extern const char * _try_;
extern const fixedstr::SFixedStr _try;
extern const char * _guardedHandlers_;
extern const fixedstr::SFixedStr _guardedHandlers;
extern const char * _TryStatement_;
extern const fixedstr::SFixedStr _TryStatement;
extern const char * _catch_;
extern const fixedstr::SFixedStr _catch;
extern const char * _CatchClause_;
extern const fixedstr::SFixedStr _CatchClause;
extern const char * _cases_;
extern const fixedstr::SFixedStr _cases;
extern const char * _tokens_;
extern const fixedstr::SFixedStr _tokens;
extern const char * _switch_;
extern const fixedstr::SFixedStr _switch;
extern const char * _discriminant_;
extern const fixedstr::SFixedStr _discriminant;
extern const char * _SwitchStatement_;
extern const fixedstr::SFixedStr _SwitchStatement;
extern const char * _continue_;
extern const fixedstr::SFixedStr _continue;
extern const char * _ContinueStatement_;
extern const fixedstr::SFixedStr _ContinueStatement;
extern const char * _regexp_;
extern const fixedstr::SFixedStr _regexp;
extern const char * _default_;
extern const fixedstr::SFixedStr _default;
extern const char * _class_;
extern const fixedstr::SFixedStr _class;
extern const char * _do_;
extern const fixedstr::SFixedStr _do;
extern const char * _DoWhileStatement_;
extern const fixedstr::SFixedStr _DoWhileStatement;
extern const char * _Program_;
extern const fixedstr::SFixedStr _Program;
extern const char * _EmptyStatement_;
extern const fixedstr::SFixedStr _EmptyStatement;
extern const char * _void_;
extern const fixedstr::SFixedStr _void;
extern const char * _finally_;
extern const fixedstr::SFixedStr _finally;
extern const char * _LabeledStatement_;
extern const fixedstr::SFixedStr _LabeledStatement;
extern const char * _errors_;
extern const fixedstr::SFixedStr _errors;
extern const char * _Line_;
extern const fixedstr::SFixedStr _Line;
extern const char * _with_;
extern const fixedstr::SFixedStr _with;
extern const char * _program_;
extern const fixedstr::SFixedStr _program;
extern const char * _lineNumber_;
extern const fixedstr::SFixedStr _lineNumber;
extern const char * _description_;
extern const fixedstr::SFixedStr _description;
extern const char * _WithStatement_;
extern const fixedstr::SFixedStr _WithStatement;
extern const char * _extends_;
extern const fixedstr::SFixedStr _extends;
extern const char * _debugger_;
extern const fixedstr::SFixedStr _debugger;
extern const char * _import_;
extern const fixedstr::SFixedStr _import;
extern const char * _export_;
extern const fixedstr::SFixedStr _export;
extern const char * _DebuggerStatement_;
extern const fixedstr::SFixedStr _DebuggerStatement;
extern const char * _comments_;
extern const fixedstr::SFixedStr _comments;
extern const char * _isAssert_;
extern const fixedstr::SFixedStr _isAssert;
extern const char * _isError_;
extern const fixedstr::SFixedStr _isError;
extern const char * _leadingComments_;
extern const fixedstr::SFixedStr _leadingComments;
extern const char * _trailingComments_;
extern const fixedstr::SFixedStr _trailingComments;
extern const char * _regexpBody_;
extern const fixedstr::SFixedStr _regexpBody;
extern const char * _regexpFlags_;
extern const fixedstr::SFixedStr _regexpFlags;
extern const char * _ArrowFunctionExpression_;
extern const fixedstr::SFixedStr _ArrowFunctionExpression;
extern const char * _ArrowParameterPlaceholder_;
extern const fixedstr::SFixedStr _ArrowParameterPlaceholder;
extern const char * _Block_;
extern const fixedstr::SFixedStr _Block;
extern const char * _const_;
extern const fixedstr::SFixedStr _const;
extern const char * _ZendZ_;
extern const fixedstr::SFixedStr _ZendZ;
extern const char * _enum_;
extern const fixedstr::SFixedStr _enum;
extern const char * _let_;
extern const fixedstr::SFixedStr _let;
extern const char * _super_;
extern const fixedstr::SFixedStr _super;
extern const char * _UnresolvedNode_;
extern const fixedstr::SFixedStr _UnresolvedNode;
extern const char * _yield_;
extern const fixedstr::SFixedStr _yield;

 extern const char * decoder[153];
#endif
#ifdef NOTEXP
extern const fixedstr::SFixedStr _line;
extern const fixedstr::SFixedStr _column;
extern const fixedstr::SFixedStr _type;
extern const fixedstr::SFixedStr _start;
extern const fixedstr::SFixedStr _end;
extern const fixedstr::SFixedStr _range;
extern const fixedstr::SFixedStr _loc;
extern const fixedstr::SFixedStr _value;
extern const fixedstr::SFixedStr _Identifier;
extern const fixedstr::SFixedStr _Punctuator;
extern const fixedstr::SFixedStr _name;
extern const fixedstr::SFixedStr _object;
extern const fixedstr::SFixedStr _property;
extern const fixedstr::SFixedStr _computed;
extern const fixedstr::SFixedStr _MemberExpression;
extern const fixedstr::SFixedStr _Keyword;
extern const fixedstr::SFixedStr _operator;
extern const fixedstr::SFixedStr _left;
extern const fixedstr::SFixedStr _right;
extern const fixedstr::SFixedStr _raw;
extern const fixedstr::SFixedStr _Literal;
extern const fixedstr::SFixedStr _expression;
extern const fixedstr::SFixedStr _arguments;
extern const fixedstr::SFixedStr _callee;
extern const fixedstr::SFixedStr _CallExpression;
extern const fixedstr::SFixedStr _init;
extern const fixedstr::SFixedStr _body;
extern const fixedstr::SFixedStr _id;
extern const fixedstr::SFixedStr _ExpressionStatement;
extern const fixedstr::SFixedStr _kind;
extern const fixedstr::SFixedStr _Numeric;
extern const fixedstr::SFixedStr _BinaryExpression;
extern const fixedstr::SFixedStr _String;
extern const fixedstr::SFixedStr _AssignmentExpression;
extern const fixedstr::SFixedStr _var;
extern const fixedstr::SFixedStr _BlockStatement;
extern const fixedstr::SFixedStr _key;
extern const fixedstr::SFixedStr _this;
extern const fixedstr::SFixedStr _ThisExpression;
extern const fixedstr::SFixedStr _VariableDeclarator;
extern const fixedstr::SFixedStr _argument;
extern const fixedstr::SFixedStr _Property;
extern const fixedstr::SFixedStr _test;
extern const fixedstr::SFixedStr _params;
extern const fixedstr::SFixedStr _consequent;
extern const fixedstr::SFixedStr _function;
extern const fixedstr::SFixedStr _defaults;
extern const fixedstr::SFixedStr _rest;
extern const fixedstr::SFixedStr _generator;
extern const fixedstr::SFixedStr _alternate;
extern const fixedstr::SFixedStr _declarations;
extern const fixedstr::SFixedStr _VariableDeclaration;
extern const fixedstr::SFixedStr _LogicalExpression;
extern const fixedstr::SFixedStr _FunctionExpression;
extern const fixedstr::SFixedStr _prefix;
extern const fixedstr::SFixedStr _return;
extern const fixedstr::SFixedStr _ReturnStatement;
extern const fixedstr::SFixedStr _if;
extern const fixedstr::SFixedStr _IfStatement;
extern const fixedstr::SFixedStr _UnaryExpression;
extern const fixedstr::SFixedStr _properties;
extern const fixedstr::SFixedStr _ObjectExpression;
extern const fixedstr::SFixedStr _elements;
extern const fixedstr::SFixedStr _ArrayExpression;
extern const fixedstr::SFixedStr _ConditionalExpression;
extern const fixedstr::SFixedStr _expressions;
extern const fixedstr::SFixedStr _SequenceExpression;
extern const fixedstr::SFixedStr _Boolean;
extern const fixedstr::SFixedStr _Null;
extern const fixedstr::SFixedStr _UpdateExpression;
extern const fixedstr::SFixedStr _for;
extern const fixedstr::SFixedStr _FunctionDeclaration;
extern const fixedstr::SFixedStr _update;
extern const fixedstr::SFixedStr _else;
extern const fixedstr::SFixedStr _ForStatement;
extern const fixedstr::SFixedStr _new;
extern const fixedstr::SFixedStr _NewExpression;
extern const fixedstr::SFixedStr _index;
extern const fixedstr::SFixedStr _typeof;
extern const fixedstr::SFixedStr _get;
extern const fixedstr::SFixedStr _in;
extern const fixedstr::SFixedStr _SwitchCase;
extern const fixedstr::SFixedStr _label;
extern const fixedstr::SFixedStr _each;
extern const fixedstr::SFixedStr _case;
extern const fixedstr::SFixedStr _RegularExpression;
extern const fixedstr::SFixedStr _break;
extern const fixedstr::SFixedStr _BreakStatement;
extern const fixedstr::SFixedStr _set;
extern const fixedstr::SFixedStr _delete;
extern const fixedstr::SFixedStr _ForInStatement;
extern const fixedstr::SFixedStr _instanceof;
extern const fixedstr::SFixedStr _while;
extern const fixedstr::SFixedStr _message;
extern const fixedstr::SFixedStr _param;
extern const fixedstr::SFixedStr _handlers;
extern const fixedstr::SFixedStr _block;
extern const fixedstr::SFixedStr _throw;
extern const fixedstr::SFixedStr _ThrowStatement;
extern const fixedstr::SFixedStr _WhileStatement;
extern const fixedstr::SFixedStr _source;
extern const fixedstr::SFixedStr _finalizer;
extern const fixedstr::SFixedStr _try;
extern const fixedstr::SFixedStr _guardedHandlers;
extern const fixedstr::SFixedStr _TryStatement;
extern const fixedstr::SFixedStr _catch;
extern const fixedstr::SFixedStr _CatchClause;
extern const fixedstr::SFixedStr _cases;
extern const fixedstr::SFixedStr _tokens;
extern const fixedstr::SFixedStr _switch;
extern const fixedstr::SFixedStr _discriminant;
extern const fixedstr::SFixedStr _SwitchStatement;
extern const fixedstr::SFixedStr _continue;
extern const fixedstr::SFixedStr _ContinueStatement;
extern const fixedstr::SFixedStr _regexp;
extern const fixedstr::SFixedStr _default;
extern const fixedstr::SFixedStr _class;
extern const fixedstr::SFixedStr _do;
extern const fixedstr::SFixedStr _DoWhileStatement;
extern const fixedstr::SFixedStr _Program;
extern const fixedstr::SFixedStr _EmptyStatement;
extern const fixedstr::SFixedStr _void;
extern const fixedstr::SFixedStr _finally;
extern const fixedstr::SFixedStr _LabeledStatement;
extern const fixedstr::SFixedStr _errors;
extern const fixedstr::SFixedStr _Line;
extern const fixedstr::SFixedStr _with;
extern const fixedstr::SFixedStr _program;
extern const fixedstr::SFixedStr _lineNumber;
extern const fixedstr::SFixedStr _description;
extern const fixedstr::SFixedStr _WithStatement;
extern const fixedstr::SFixedStr _extends;
extern const fixedstr::SFixedStr _debugger;
extern const fixedstr::SFixedStr _import;
extern const fixedstr::SFixedStr _export;
extern const fixedstr::SFixedStr _DebuggerStatement;
extern const fixedstr::SFixedStr _comments;
extern const fixedstr::SFixedStr _isAssert;
extern const fixedstr::SFixedStr _isError;
extern const fixedstr::SFixedStr _leadingComments;
extern const fixedstr::SFixedStr _trailingComments;
extern const fixedstr::SFixedStr _regexpBody;
extern const fixedstr::SFixedStr _regexpFlags;
extern const fixedstr::SFixedStr _ArrowFunctionExpression;
extern const fixedstr::SFixedStr _ArrowParameterPlaceholder;
extern const fixedstr::SFixedStr _Block;
extern const fixedstr::SFixedStr _const;
extern const fixedstr::SFixedStr _ZendZ;
extern const fixedstr::SFixedStr _enum;
extern const fixedstr::SFixedStr _let;
extern const fixedstr::SFixedStr _super;
extern const fixedstr::SFixedStr _UnresolvedNode;
extern const fixedstr::SFixedStr _yield;
#endif
}

#endif
